### ISSUE TITLE
compile error in jimtcl configure stage with -D-DESP_PLATFORM (OCDOE-6)

### ISSUE THREAD

**Issue by 442534820** [espressif/openocd-on-esp32#2]
my sdk version is release/v5.0
error message is “Checking for stdlib.h...not found” in jimctl.
I found that configure action in jimctl with -D-DESP_PLATFORM will cause this error，but clearly it is a global define. what should I do with this error

here is log below
cloud@LAPTOP-HMM2SVIK:/mnt/e/tmp/openocd-on-esp32$ idf.py all
Executing action: all (aliases: build)
Running ninja in directory /mnt/e/tmp/openocd-on-esp32/build
Executing "ninja all"...
[0/963] Performing configure step for 'jimtcl_build'Host System...xtensa-esp32s3-elf
Build System...x86_64-pc-linux-gnu
C compiler...ccache xtensa-esp32s3-elf-cc -mlongcalls  -I/mnt/e/tmp/openocd-on-esp32/components/jimtcl/../platform_include -I/mnt/e/tmp/openocd-on-esp32/components/jimtcl/jimtcl -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/newlib/platform_include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/mnt/e/linux_work/esp-idf/components/freertos/esp_additions/include/freertos -I/mnt/e/linux_work/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/mnt/e/linux_work/esp-idf/components/freertos/esp_additions/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/include -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/include/soc -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/include/soc/esp32s3 -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/port/esp32s3/. -I/mnt/e/linux_work/esp-idf/components/heap/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/log/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/soc/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/soc/esp32s3/. -I/mnt/e/linux_work/esp-idf/components/soc/esp32s3/include -I/mnt/e/linux_work/esp-idf/components/hal/esp32s3/include -I/mnt/e/linux_work/esp-idf/components/hal/include -I/mnt/e/linux_work/esp-idf/components/hal/platform_port/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_rom/include -I/mnt/e/linux_work/esp-idf/components/esp_rom/include/esp32s3 -I/mnt/e/linux_work/esp-idf/components/esp_rom/esp32s3 -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_common/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_system/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_system/port/soc -I/mnt/e/linux_work/esp-idf/components/esp_system/port/include/private -I/mnt/e/linux_work/esp-idf/components/xtensa/include -I/mnt/e/linux_work/esp-idf/components/xtensa/esp32s3/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/lwip/include -I/mnt/e/linux_work/esp-idf/components/lwip/include/apps -I/mnt/e/linux_work/esp-idf/components/lwip/include/apps/sntp -I/mnt/e/linux_work/esp-idf/components/lwip/lwip/src/include -I/mnt/e/linux_work/esp-idf/components/lwip/port/esp32/include -I/mnt/e/linux_work/esp-idf/components/lwip/port/esp32/include/arch -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/pthread/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/vfs/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/tmp/openocd-on-esp32/components/jimtcl/jimtcl -I/mnt/e/tmp/openocd-on-esp32/build/config -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -O2 -fmacro-prefix-map=/mnt/e/tmp/openocd-on-esp32=. -fmacro-prefix-map=/mnt/e/linux_work/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -D-D_GNU_SOURCE -D-DIDF_VER="v5.0.5-166-g209a0361c0" -D-DESP_PLATFORM -D-D_POSIX_READER_WRITER_LOCKS -Wno-implicit-fallthrough -Wno-missing-field-initializers -DHAVE_USLEEP=1
C++ compiler...ccache xtensa-esp32s3-elf-c++ -mlongcalls  -I/mnt/e/tmp/openocd-on-esp32/components/jimtcl/../platform_include -I/mnt/e/tmp/openocd-on-esp32/components/jimtcl/jimtcl -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/newlib/platform_include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/mnt/e/linux_work/esp-idf/components/freertos/esp_additions/include/freertos -I/mnt/e/linux_work/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/mnt/e/linux_work/esp-idf/components/freertos/esp_additions/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/include -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/include/soc -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/include/soc/esp32s3 -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/port/esp32s3/. -I/mnt/e/linux_work/esp-idf/components/heap/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/log/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/soc/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/soc/esp32s3/. -I/mnt/e/linux_work/esp-idf/components/soc/esp32s3/include -I/mnt/e/linux_work/esp-idf/components/hal/esp32s3/include -I/mnt/e/linux_work/esp-idf/components/hal/include -I/mnt/e/linux_work/esp-idf/components/hal/platform_port/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_rom/include -I/mnt/e/linux_work/esp-idf/components/esp_rom/include/esp32s3 -I/mnt/e/linux_work/esp-idf/components/esp_rom/esp32s3 -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_common/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_system/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_system/port/soc -I/mnt/e/linux_work/esp-idf/components/esp_system/port/include/private -I/mnt/e/linux_work/esp-idf/components/xtensa/include -I/mnt/e/linux_work/esp-idf/components/xtensa/esp32s3/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/lwip/include -I/mnt/e/linux_work/esp-idf/components/lwip/include/apps -I/mnt/e/linux_work/esp-idf/components/lwip/include/apps/sntp -I/mnt/e/linux_work/esp-idf/components/lwip/lwip/src/include -I/mnt/e/linux_work/esp-idf/components/lwip/port/esp32/include -I/mnt/e/linux_work/esp-idf/components/lwip/port/esp32/include/arch -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/pthread/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/vfs/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/tmp/openocd-on-esp32/components/jimtcl/jimtcl -I/mnt/e/tmp/openocd-on-esp32/build/config -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -O2 -fmacro-prefix-map=/mnt/e/tmp/openocd-on-esp32=. -fmacro-prefix-map=/mnt/e/linux_work/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -D-D_GNU_SOURCE -D-DIDF_VER="v5.0.5-166-g209a0361c0" -D-DESP_PLATFORM -D-D_POSIX_READER_WRITER_LOCKS -Wno-implicit-fallthrough -Wno-missing-field-initializers -DHAVE_USLEEP=1
Build C compiler...cc
Checking for stdlib.h...not found
Error: Compiler does not work. See config.log
Try: 'configure --help' for options
[1/1] cd /mnt/e/tmp/openocd-on-esp32/build/bootloader/esp-idf/...x0 /mnt/e/tmp/openocd-on-esp32/build/bootloader/bootloader.bi
Bootloader binary size 0x5040 bytes. 0x2fc0 bytes (37%) free.
[14/961] Linking C static library esp-idf/newlib/libnewlib.aFAILED: ../components/jimtcl/src/jimtcl_build-stamp/jimtcl_build-configure
cd /mnt/e/tmp/openocd-on-esp32/components/jimtcl/jimtcl && ./configure --disable-install-jim --with-ext=json --minimal --disable-ssl --host=xtensa-esp32s3-elf "CFLAGS=-mlongcalls  -I/mnt/e/tmp/openocd-on-esp32/components/jimtcl/../platform_include -I/mnt/e/tmp/openocd-on-esp32/components/jimtcl/jimtcl -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/newlib/platform_include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/mnt/e/linux_work/esp-idf/components/freertos/esp_additions/include/freertos -I/mnt/e/linux_work/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/mnt/e/linux_work/esp-idf/components/freertos/esp_additions/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/include -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/include/soc -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/include/soc/esp32s3 -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_hw_support/port/esp32s3/. -I/mnt/e/linux_work/esp-idf/components/heap/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/log/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/soc/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/soc/esp32s3/. -I/mnt/e/linux_work/esp-idf/components/soc/esp32s3/include -I/mnt/e/linux_work/esp-idf/components/hal/esp32s3/include -I/mnt/e/linux_work/esp-idf/components/hal/include -I/mnt/e/linux_work/esp-idf/components/hal/platform_port/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_rom/include -I/mnt/e/linux_work/esp-idf/components/esp_rom/include/esp32s3 -I/mnt/e/linux_work/esp-idf/components/esp_rom/esp32s3 -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_common/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_system/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/esp_system/port/soc -I/mnt/e/linux_work/esp-idf/components/esp_system/port/include/private -I/mnt/e/linux_work/esp-idf/components/xtensa/include -I/mnt/e/linux_work/esp-idf/components/xtensa/esp32s3/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/lwip/include -I/mnt/e/linux_work/esp-idf/components/lwip/include/apps -I/mnt/e/linux_work/esp-idf/components/lwip/include/apps/sntp -I/mnt/e/linux_work/esp-idf/components/lwip/lwip/src/include -I/mnt/e/linux_work/esp-idf/components/lwip/port/esp32/include -I/mnt/e/linux_work/esp-idf/components/lwip/port/esp32/include/arch -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/pthread/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/linux_work/esp-idf/components/vfs/include -I/mnt/e/tmp/openocd-on-esp32/build/config -I/mnt/e/tmp/openocd-on-esp32/components/jimtcl/jimtcl -I/mnt/e/tmp/openocd-on-esp32/build/config -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -O2 -fmacro-prefix-map=/mnt/e/tmp/openocd-on-esp32=. -fmacro-prefix-map=/mnt/e/linux_work/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -D-D_GNU_SOURCE -D-DIDF_VER=\"v5.0.5-166-g209a0361c0\" -D-DESP_PLATFORM -D-D_POSIX_READER_WRITER_LOCKS -Wno-implicit-fallthrough -Wno-missing-field-initializers -DHAVE_USLEEP=1" && /usr/local/bin/cmake -E touch /mnt/e/tmp/openocd-on-esp32/components/jimtcl/src/jimtcl_build-stamp/jimtcl_build-configure
[16/961] Linking C static library esp-idf/freertos/libfreertos.aninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /mnt/e/tmp/openocd-on-esp32/build/log/idf_py_stderr_output_4692 and /mnt/e/tmp/openocd-on-esp32/build/log/idf_py_stdout_output_4692

**Comment by erhankur** [comment]
We don't plan to support earlier IDF versions in this repo. Can you check out the idf master and try to rebuild it with a clean environment?

**Comment by igrr** [comment]
This is probably related to the change in IDF v5.1: https://github.com/espressif/esp-idf/commit/c392c06216c5894267f398df56657cb3e415fbfa

And we should update the Readme file if we don't support v5.0. Better to also add release branches we support to the CI workflow.

**Comment by 442534820** [comment]
thanks for help  :)
I checkout the master branch and rebuild it , it works.
It semms that v5.0/v5.1/v5.2 is not suitable for this repo.
Notice 'Supported IDF versions' is 5.0 or later in README

**Comment by erhankur** [comment]
> This is probably related to the change in IDF v5.1: [espressif/esp-idf@c392c06](https://github.com/espressif/esp-idf/commit/c392c06216c5894267f398df56657cb3e415fbfa)
> 
> And we should update the Readme file if we don't support v5.0. Better to also add release branches we support to the CI workflow.

After the replacement of deprecated `esp_vfs_xxx` functions, 5.1 and 5.2 builds were also broken. I have fixed them. So, no reason to opt out 5.0 now. I have also fixed the double definition of `ESP_PLATFORM`  

Changes will be merged here soon.

**Comment by erhankur** [comment]
@442534820 Now it is OK to build with idf 5.0...5.3 fyi
