### ISSUE TITLE
usage error: Cannot connect to remote gdb server when running xtensa-esp32-elf-gdb (OCDOE-10)

### ISSUE THREAD

**Issue by MGasparov** [espressif/openocd-on-esp32#5]
When I try to connect via gdb client (xtensa-esp32-elf-gdb) to gdb server I run the following commands:
`xtensa-esp32-elf-gdb
file build/helloworld.elf
target extended-remote 192.168.4.1:3333`

In turn I get the following error message from the log output of the gdb server running on esp32s3 box:

`Info : accepting 'gdb' connection on tcp/3333
Error: Target not examined yet
Error executing event gdb-attach on target esp32.cpu0:
/data/target/esp_common.cfg:9: Error:
at file "/data/target/esp_common.cfg", line 9
Warn : No symbols for FreeRTOS!
Error: Target not halted
Error: auto_probe failed
Error: Connect failed. Consider setting up a gdb-attach event for the target to prepare target for GDB connect, or use 'gdb_memory_map disable'.
Error: attempted 'gdb' connection rejected`

I have tried changing various settings in the web interface but to no success.

**Comment by erhankur** [comment]
@MGasparov Are you sure ESP-BOX and your target (ESP32) jtag pins connection is correct? You can monitor ESP-BOX logs and see the OpenOCD initial output.

**Comment by MGasparov** [comment]
Yes they are connected properly, I have managed to get it to work by reseting the UART connection with the ESP-BOX. Occasionally it would not recognise the ESP32 it is connected to, after the connection reset it would recognise the ESP.

**Comment by erhankur** [comment]
Before the GDB connection, it may need to reset for proper OpenOCD init process. We plan to inform users through the ESP-BOX screen about that kind of failure. 

I am closing this. Let us know if you see any other issues during debugging.
