### ISSUE TITLE
Running with 2M PSRAM ? (OCDOE-12)

### ISSUE THREAD

**Issue by solosky** [espressif/openocd-on-esp32#6]
Hi,

Thanks for the great project,  and I tested on my ESP32S3 eval board, all functions work as a charm. 

Meanwhile, I am working my hardware version for this project, I would like to choose 2M PSRAM chip to build this. 
I just print out the SPI PSRAM usage, I found the maximum usage is about 1.2MB memory size, which indicates that the project could be run on 2M PSRAM. 

I just want to know that,  
* Have you try run the project on the ESP32S3 with 2M PSRAM? 
* Is it possible to run this project smoothly with 2M PSRAM? 
*  What‘s the minimum PSRAM requirement for this project?

**Comment by erhankur** [comment]
Hi @solosky it is nice to hear you have managed to work it without an issue.

Yes, I tested basic debugging with a 2MB PSRAM devkit. It was fine. Unfortunately, I didn't check how much PSRAM memory was used during runtime. So I can't say the exact number now. But 1.2MB looks reasonable. 

When you design your PSRAM hardware, please check the IDF support of course. For the octal type, afaik, min 4MB is required.

Keep in mind that with the addition of (UI) LVGL, PSRAM usage may also increase.
